name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches:
      - master    # or your default branch
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: cd frontend-new && npm install

      - name: Build
        run: cd frontend-new && export NODE_OPTIONS=--openssl-legacy-provider && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend-new/dist
